#!/usr/bin/env python3

import sys
import re
import struct
import time

poly4 = 1
poly5 = 1
poly17 = 1

def calc_poly4(v): return (v<<1) | ( ((v>>2) ^ (v>>3)) & 1)
def calc_poly5(v): return (v<<1) | ( ((v>>2) ^ (v>>4)) & 0x1)
def calc_poly9(v): return (v<<1) | ( ((v>>3) ^ (v>>8)) & 0x1)
def calc_poly17(v): return (v<<1) & 0xffffffff | ( ((v>>2) ^ (v>>16)) & 0x1)

poly4_lookup = []
poly5_lookup = []

n = 1
for i in range(15): poly4_lookup.append(n := calc_poly4(n))
n = 1
for i in range(31): poly5_lookup.append(n := calc_poly5(n))

def check_poly(dist, value):
	global poly4
	global poly5
	global poly17
	if(dist & 0x8):
		return (value+1 if dist & 0x2 else poly4 if dist & 0x4 else poly17) & 1
	return (poly5 if dist & 0x2 else poly5 & poly4 if dist & 0x4 else poly5 & poly17) & 1

scounter = 0

channel_values = [0] * 8
channel_next = [0] * 8
channel_audf = [0] * 8

def generate_pokey(data1, audsize):
	global scounter
	global poly4
	global poly5
	global poly17
	data = list(data1)

#	acounter = ( scounter + acounter_remain ) // rate
#	acounter_remain = ( scounter + acounter_remain ) % rate

	if(scounter): poly17 = calc_poly17(poly17)

	outlist = []
	append = outlist.append
	

	for p in range(audsize // 9):
		ratem = rate

		audctl = data[p * 9 + 8]
		#if(p == 1): print(f" audctl {p} = {bin(audctl)}", file=sys.stderr)
		out = 0
		if(audctl & 1):
			ratem = rate * 4

	#	print(f"ratem {p} ratem {ratem}", file=sys.stderr)
		ratea = ratem
		rateb = ratem

		if(audctl & 0x20):
			ratea = rate // 28

		if(audctl & 0x40):
			rateb = rate // 28
			
		if(audctl & 0x10):
			data[0] = data[2] << 8 | data[0]
			data[1] = data[3]
			data[2] = 0
			data[3] = 0
		if(audctl & 0x8):
			data[4] = data[6] << 8 | data[4]
			data[5] = data[7]
			data[6] = 0
			data[7] = 0
		for i in range(4):
			ratex = ratem #ratea if i == 0 else rateb if i == 2 else ratem
			#if(p == 1): print(f"ratex {i} {ratex}", file=sys.stderr)
			audf = data[p * 9 + (i << 1)]
			audc = data[(p * 9 + (i << 1)) + 1]
			volume = audc & 0xf
			dist = audc >> 4
			if 0 == audf: continue

			if (0 == channel_audf[i] and 0 != audf or arate > (scounter % (ratex * (channel_audf[i] + 1)))):
				channel_audf[i] = audf
				acounter = int(channel_next[i] // ratex)
				poly4 = poly4_lookup[acounter % 15]
				poly5 = poly5_lookup[acounter % 31]
				channel_values[i] = check_poly(dist, channel_values[i])
				channel_next[i] = channel_next[i] + (audf + 1) * ratex
			out += channel_values[i] and volume
		append(out)

	scounter += arate
	if(scounter == rate * arate): sounter = 0

	return outlist

def combine_channels(data, combine_size = 1):
	if combine_size == 4:
		return [ sum(data)]
	elif combine_size == 2:
		return [ sum([value << 0 for value in data ]) ]
	else:
		return [ value << 0 for value in data ]


audsize = 9
fastplay = 262

while(None != (data := sys.stdin.buffer.readline(128))):
	if(re.match(b'\xff\xff', data)):
		if(data[2] == 0 and data[3] == 0):
			data = data[6:]
		else:
			data = data[2:]
		break
	data = data.rstrip()
	if(0 == len(data)): break

	if(re.match(b'STEREO', data)): audsize = 18
	if(m := re.match(b'FASTPLAY ', data)): fastplay = int(m.string[m.end():])

import wave

outwav = wave.open(sys.stdout.buffer, "wb")

combine_pokey_channels = False

pokey_count = audsize // 9
output_channels = pokey_count
combine_size = 1
if(combine_pokey_channels):
	if 0 == pokey_count % 4:
		output_channels = pokey_count // 4
		combine_size = 4
	elif 0 == pokey_count % 2:
		output_channels = pokey_count // 2
		combine_size = 2

outwav.setnchannels(output_channels)
outwav.setsampwidth(1)
rate = 24000
arate = 63920

outwav.setframerate(rate)

while(None != data):
	if(0 == len(data)):
		data = sys.stdin.buffer.read(audsize)
		if(None is data): break
	elif(len(data) < audsize):
		newdata = sys.stdin.buffer.read(audsize - len(data))
		if(None is newdata): break
		data = data + newdata

	if(len(data) < audsize): break

	#start = time.clock_gettime_ns(time.CLOCK_MONOTONIC)
	outdata = [combine_channels(generate_pokey(data, audsize), combine_size) for i in range(fastplay * 114 // 28 * rate // arate)]
	outwav.writeframesraw(bytearray([value for values in outdata for value in values]))

	#elapsed = time.clock_gettime_ns(time.CLOCK_MONOTONIC)
	#elapsed = elapsed - start
	#rint (f"Time spent in function {elapsed}", file=sys.stderr)

	data = data[audsize:]

outwav.close()
